services:
    forumhulp.pageaddon.listener:
        class: forumhulp\pageaddon\event\listener
        arguments:
            - @controller.helper
            - @user
            - @template
            - @service_container
            - @request
        tags:
            - { name: event.listener }
